/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package DiplomskiRad;

import java.io.IOException;
import java.security.GeneralSecurityException;

public class App {

    public static void main(String... args) throws IOException, GeneralSecurityException {
        //GoogleDriveOperations drv = new GoogleDriveOperations();//("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",
        //"1EK7CISqSAFwzBaRh9gJJ5JMwV3buCAts");
        //drv.downloadFile();
        //drv.searchFile();
        //drv.updateFile();
        //drv.logout();
        //JSONfiles.writeToJSONfile();
        boolean c = true;
        boolean d = false;
        if (c) {
            JSONfiles.readFromJSONfile();
            java.awt.EventQueue.invokeLater(() -> {
                ShowGUI gui = new ShowGUI();
                gui.setVisible(true);
            });
        } else {
            boolean a = true;
            boolean b = false;
            String salt = "1qTNsaC-Aq6fxl2HjqJVdXMbKsGsSZx_9";

            if (b) {
                AESalgorithm.encryptFile("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", salt);
            } else {
                AESalgorithm.decryptFile("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", salt);
            }

        }


    }
}
