/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package DiplomskiRad;

import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.StringSelection;
import java.io.IOException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;

/**
 *
 * @author PC
 */
public class ShowGUI extends javax.swing.JFrame {

    /**
     * Creates new form ShowGUI
     */
    public ShowGUI() {
        initComponents();
        ImageIcon img = new ImageIcon("..\\app\\src\\main\\resources\\pictures\\keyIcon.png");
        this.setIconImage(img.getImage());
    }

    private GoogleDriveOperations drv;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popMenu = new javax.swing.JPopupMenu();
        copyItem = new javax.swing.JMenuItem();
        pasteItem = new javax.swing.JMenuItem();
        parentPanel = new javax.swing.JPanel();
        panelStart = new javax.swing.JPanel();
        sifra = new javax.swing.JPasswordField();
        this.sifra.setEnabled(false);
        passButton = new javax.swing.JButton();
        this.passButton.setEnabled(false);
        jLabel2 = new javax.swing.JLabel();
        logInButton = new javax.swing.JButton();
        panelLoggedIn = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        addButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();
        genButton = new javax.swing.JButton();
        genPass = new javax.swing.JTextField();
        changeButton = new javax.swing.JButton();
        NoPassPanel = new javax.swing.JPanel();
        submitButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();

        copyItem.setText("copy");
        popMenu.add(copyItem);

        pasteItem.setText("paste");
        popMenu.add(pasteItem);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        parentPanel.setLayout(new java.awt.CardLayout());

        panelStart.setPreferredSize(new java.awt.Dimension(653, 384));

        passButton.setText("Log In pass");
        passButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passButtonActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/key.png"))); // NOI18N

        logInButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/googleLogIn.png"))); // NOI18N
        logInButton.setToolTipText("");
        logInButton.setActionCommand("LogIn");
        logInButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logInButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelStartLayout = new javax.swing.GroupLayout(panelStart);
        panelStart.setLayout(panelStartLayout);
        panelStartLayout.setHorizontalGroup(
            panelStartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelStartLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(257, 257, 257))
            .addGroup(panelStartLayout.createSequentialGroup()
                .addGroup(panelStartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelStartLayout.createSequentialGroup()
                        .addGap(226, 226, 226)
                        .addComponent(logInButton, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelStartLayout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addComponent(sifra, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(passButton)))
                .addContainerGap(258, Short.MAX_VALUE))
        );
        panelStartLayout.setVerticalGroup(
            panelStartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelStartLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel2)
                .addGap(39, 39, 39)
                .addComponent(logInButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelStartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sifra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passButton))
                .addGap(71, 71, 71))
        );

        parentPanel.add(panelStart, "card2");

        panelLoggedIn.setPreferredSize(new java.awt.Dimension(700, 500));

        jLabel1.setText("You are logged in!");

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Website", "Username", "Password", "Strength", "Date&Time"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, true, true, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabela.setColumnSelectionAllowed(true);
        tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tabelaMouseReleased(evt);
            }
        });
        tabela.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tabelaPropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(tabela);
        tabela.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        addButton.setText("add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        deleteButton.setText("delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        saveButton.setText("save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        logoutButton.setText("log out");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        genButton.setText("Generate password");
        genButton.setToolTipText("");
        genButton.setActionCommand("");
        genButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genButtonActionPerformed(evt);
            }
        });

        changeButton.setText("change password");
        changeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLoggedInLayout = new javax.swing.GroupLayout(panelLoggedIn);
        panelLoggedIn.setLayout(panelLoggedInLayout);
        panelLoggedInLayout.setHorizontalGroup(
            panelLoggedInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLoggedInLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(panelLoggedInLayout.createSequentialGroup()
                .addGroup(panelLoggedInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLoggedInLayout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(addButton)
                        .addGap(38, 38, 38)
                        .addComponent(deleteButton)
                        .addGap(41, 41, 41)
                        .addComponent(saveButton)
                        .addGap(38, 38, 38)
                        .addComponent(logoutButton))
                    .addGroup(panelLoggedInLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(panelLoggedInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelLoggedInLayout.createSequentialGroup()
                                .addComponent(genButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(genPass, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)
                                .addComponent(changeButton))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 634, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        panelLoggedInLayout.setVerticalGroup(
            panelLoggedInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLoggedInLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(panelLoggedInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addButton)
                    .addComponent(deleteButton)
                    .addComponent(saveButton)
                    .addComponent(logoutButton))
                .addGap(32, 32, 32)
                .addGroup(panelLoggedInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genButton)
                    .addComponent(genPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(changeButton))
                .addContainerGap(79, Short.MAX_VALUE))
        );

        parentPanel.add(panelLoggedIn, "card3");

        submitButton.setText("SUBMIT");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("Choose password");

        jLabel4.setText("Confirm password");

        jLabel5.setText("Create password");

        javax.swing.GroupLayout NoPassPanelLayout = new javax.swing.GroupLayout(NoPassPanel);
        NoPassPanel.setLayout(NoPassPanelLayout);
        NoPassPanelLayout.setHorizontalGroup(
            NoPassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NoPassPanelLayout.createSequentialGroup()
                .addGroup(NoPassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NoPassPanelLayout.createSequentialGroup()
                        .addGap(249, 249, 249)
                        .addComponent(submitButton))
                    .addGroup(NoPassPanelLayout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(jLabel5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(NoPassPanelLayout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(NoPassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addGroup(NoPassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(338, Short.MAX_VALUE))
        );
        NoPassPanelLayout.setVerticalGroup(
            NoPassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NoPassPanelLayout.createSequentialGroup()
                .addContainerGap(203, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(27, 27, 27)
                .addGroup(NoPassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(NoPassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addComponent(submitButton)
                .addGap(86, 86, 86))
        );

        parentPanel.add(NoPassPanel, "card4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(parentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(parentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 433, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logInButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logInButtonActionPerformed
        this.drv = new GoogleDriveOperations();
        if(!this.drv.isLogged()){
            parentPanel.removeAll();
            parentPanel.add(NoPassPanel);
            parentPanel.repaint();
            parentPanel.revalidate();
        }
        this.passButton.setEnabled(true);
        this.sifra.setEnabled(true);
    }//GEN-LAST:event_logInButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        
        DefaultTableModel tblModel = (DefaultTableModel) tabela.getModel();
        LocalDateTime myDateObj = LocalDateTime.now();
        DateTimeFormatter myFormatObj = DateTimeFormatter.ofPattern("dd-MM-yyyy HH:mm:ss");
        String formattedDate = myDateObj.format(myFormatObj);
        String niz[] = {"", "", "", "", formattedDate};
        tblModel.addRow(niz);
    }//GEN-LAST:event_addButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        
        DefaultTableModel tblModel = (DefaultTableModel) tabela.getModel();
        if(this.tabela.getSelectedColumnCount() == 1){
            tblModel.removeRow(this.tabela.getSelectedRow());
        } else {
            if(this.tabela.getRowCount() == 0){
                JOptionPane.showMessageDialog(parentPanel, "Table is empty");
            }
            else JOptionPane.showMessageDialog(parentPanel, "Select one row");
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        this.saveAllPassToCloud(true);
    }//GEN-LAST:event_saveButtonActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        this.saveAllPassToCloud(false);
        drv.logout();
        parentPanel.removeAll();
        parentPanel.add(panelStart);
        parentPanel.repaint();
        parentPanel.revalidate();
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void genButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genButtonActionPerformed
        String pass = StrongPassword.generatePassword();
        this.genPass.setText(pass);
        Clipboard clp = Toolkit.getDefaultToolkit().getSystemClipboard();
        StringSelection s1 = new StringSelection(pass);
        clp.setContents(s1, null);
    }//GEN-LAST:event_genButtonActionPerformed

    private void passButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passButtonActionPerformed
        
        drv.updatePassword(new String(this.sifra.getPassword()));
        if (drv.isGoodPassword()) {
            String correctPass = JSONfiles.getPassForThis();
            String insertedPass = new String(this.sifra.getPassword());
            System.out.println("ShowGUI -> passButton -> insertPass/correctPass: " + insertedPass + "/" + correctPass);
            parentPanel.removeAll();
            parentPanel.add(panelLoggedIn);
            parentPanel.repaint();
            parentPanel.revalidate();
            this.repaintTable();
        } else {
            JOptionPane.showMessageDialog(null, "Your password is not correct", "Notification", 1);
        }
    }//GEN-LAST:event_passButtonActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        String pass1 = new String(this.jPasswordField1.getPassword());
        String pass2 = new String(this.jPasswordField2.getPassword());
        if(pass1.equals(pass2)){
            drv.setPassword(pass1);
            JOptionPane.showMessageDialog(null, "Your password is in use", "Notification", 1);
            parentPanel.removeAll();
            parentPanel.add(panelLoggedIn);
            parentPanel.repaint();
            parentPanel.revalidate();
            this.repaintTable();
        }
        else {
            JOptionPane.showMessageDialog(null, "Passwords are not equal", "Notification", 1);
        }
        
    }//GEN-LAST:event_submitButtonActionPerformed

    private void changeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeButtonActionPerformed
        parentPanel.removeAll();
        parentPanel.add(NoPassPanel);
        parentPanel.repaint();
        parentPanel.revalidate();
        DefaultTableModel tblModel = (DefaultTableModel) tabela.getModel();
        for (int i = 0; i < tblModel.getRowCount(); i++) {
            tblModel.removeRow(i);
        }
    }//GEN-LAST:event_changeButtonActionPerformed

    private void tabelaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tabelaPropertyChange
        DefaultTableModel tblModel = (DefaultTableModel) tabela.getModel();
        for (int i = 0; i < tblModel.getRowCount(); i++) {
            String pass = tblModel.getValueAt(i, 2).toString();
            System.out.println("ShowGUI -> tabelaUpdate : " + pass);
            String strength = StrongPassword.passwordCheck(pass);
            tblModel.setValueAt(strength, i, 3);
        }
        tabela.repaint();
        //JOptionPane.showMessageDialog(null, "Updated", "Notification", 1);
    }//GEN-LAST:event_tabelaPropertyChange

    private void tabelaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseReleased
        if(evt.isPopupTrigger()){
            popMenu.show(this, evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_tabelaMouseReleased

    private void repaintTable(){
        JSONArray lista = JSONfiles.readFromJSONfile();
        if(lista == null || lista.isEmpty()) return;
        DefaultTableModel tblModel = (DefaultTableModel) tabela.getModel();
        for (Object object : lista) {
            JSONObject obj1 = (JSONObject) object;
            String niz[] = JSONfiles.parseObject(obj1);
            tblModel.addRow(niz);
        }
    }
    
    private void saveAllPassToCloud(boolean b) {
        DefaultTableModel tblModel = (DefaultTableModel) tabela.getModel();
        Object objekti[] = tblModel.getDataVector().toArray();
        System.out.println(tblModel.getDataVector().toString());
        JSONfiles.rewriteJSONfile(objekti);
        try {
            drv.updateFile();
        } catch (IOException ex) {
            Logger.getLogger(ShowGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(b) JOptionPane.showMessageDialog(null, "Your passwords are updated", "Notification", 1);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShowGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShowGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShowGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShowGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            ShowGUI gui = new ShowGUI();
            gui.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel NoPassPanel;
    private javax.swing.JButton addButton;
    private javax.swing.JButton changeButton;
    private javax.swing.JMenuItem copyItem;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton genButton;
    private javax.swing.JTextField genPass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton logInButton;
    private javax.swing.JButton logoutButton;
    private javax.swing.JPanel panelLoggedIn;
    private javax.swing.JPanel panelStart;
    private javax.swing.JPanel parentPanel;
    private javax.swing.JButton passButton;
    private javax.swing.JMenuItem pasteItem;
    private javax.swing.JPopupMenu popMenu;
    private javax.swing.JButton saveButton;
    private javax.swing.JPasswordField sifra;
    private javax.swing.JButton submitButton;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables

}
